name: Pull Request - Testes com Jest

on: 
  push: 
    branches: 
      - main

jobs: 
  publish: 
    name: Teste
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x

      - run: npm
      - run: npm run test