name: Pull Request - Testes com Jest

on: 
  push: 
    branches: 
      - master

jobs: 
  publish: 
    name: Teste
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm run test